name: C++ CI

on:
  push:
    branches: [main, evaluate]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake
          sudo apt-get install -y libcurl4-openssl-dev

      - name: Install CMake targets
        run: |
          sudo cmake --install .

      - name: Build and test
        run: |
          mkdir build && cd build
          cmake ..
          make
          ctest
