name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Generate CMake file
      run: |
        # generate CMake file here
        cmake -S . -B build
      working-directory: ${{ github.workspace }}

    - name: configure
      run: cmake --build build --config Release
      working-directory: ${{ github.workspace }}

    - name: run program and check exit code
      run: |
        # run compiled program here
        ./build/turing-text
        if [ $? -ne 0 ]; then exit 1; fi
      working-directory: ${{ github.workspace }}
