name: C/C++ CI

on:
  push:
    branches:
      - evaluate

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Compile and test each file
      run: |
        for file in $(git diff --name-only HEAD~1); do
          if [[ $file == *.cpp ]]; then
            echo "Compiling $file"
            g++ $file -o "${file%.*}"
            if [ $? -ne 0 ]; then
              echo "Compilation of $file failed"
              exit 1
            fi
            echo "Running $file"
            "./${file%.*}"
            if [ $? -ne 0 ]; then
              echo "Test of $file failed"
              exit 1
            fi
          fi
        done
      working-directory: ${{ github.workspace }}

    - name: Merge changes into main branch
      run: |
        git checkout main
        git merge evaluate
        git push origin main
      working-directory: ${{ github.workspace }}
