name: CI

on:
  push:
    branches:
      - evaluate
  schedule:
    - cron: '0 2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and Test
        run: |
          mkdir build
          cd build
          cmake ..
          make
          ctest
        working-directory: ./evaluate

      - name: Merge to Main
        if: ${{ success() }}
        run: |
          git checkout main
          git merge --no-ff evaluate -m "Merge evaluate branch"
          git push
        working-directory: ${{ github.workspace }}
